[package]
name = "egui-demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1.1", features = ["enable-glwindow"] }
gl = "0.14.0"
egui = "0.14.0"
fltk-egui = "0.1"