[package]
authors = ["Mohammed Alyousef <may642_2000@hotmail.com>"]
name = "cairo_button"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = { version = "^1.4", features = ["use-ninja"] }
cairo-rs = "0.18"
cairo-blur = "^0.1"
